# -*- coding: utf-8 -*-
"""Assignment 18

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12bfvQBEUSCLwsTd5BbmLX8cIqk0SSgIg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("ford_car_dataset.csv")
df.head(10)

print(df.tail())

print("Shape:", df.shape)

print(df.dtypes)

print(df.info())

# Missing values
print(df.isnull().sum())

# Duplicate rows
print("Duplicate Rows:", df.duplicated().sum())

# Remove duplicates
df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

# Statistical summary
print(df.describe())

# Minimum values
print("Minimum Values")
print(df[['price', 'mileage', 'year']].min())

# Maximum values
print("Maximum Values")
print(df[['price', 'mileage', 'year']].max())

# Mean values
print("Mean Values")
print(df[['price', 'mileage', 'year']].mean())

# Median values
print("Median Values")
print(df[['price', 'mileage', 'year']].median())

import matplotlib.pyplot as plt

numeric_cols = ['price', 'mileage', 'year', 'engineSize', 'mpg']

df[numeric_cols].hist(figsize=(12,8), bins=20)

plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

categorical_cols = ['model', 'transmission', 'fuelType']

for col in categorical_cols:
    plt.figure(figsize=(8,5))
    sns.countplot(x=col, data=df)
    plt.xticks(rotation=45)
    plt.title(col)
    plt.show()

# Observation:
# Identify the most common models, fuel types, and transmissions.

import seaborn as sns
import matplotlib.pyplot as plt

corr = df.corr(numeric_only=True)

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap='coolwarm')

plt.title("Correlation Heatmap")
plt.show()

# Correlation with price
print(corr['price'].sort_values(ascending=False))

# Observation:
# Identify features most correlated with price.

# Independent Features
X = df.drop('price', axis=1)

# Dependent Feature
y = df['price']

print("Independent Features:")
print(X.columns)

print("\nDependent Feature:")
print(y.name)

# Justification:
# Price is the target variable because it is being predicted.

# Before Encoding
print(df[['fuelType', 'transmission']].head())

# One Hot Encoding
df_encoded = pd.get_dummies(df, drop_first=True)

# After Encoding
print(df_encoded.head())

# Encoded column names
print(df_encoded.columns)

from sklearn.preprocessing import StandardScaler

numeric_features = ['year', 'mileage', 'tax', 'mpg', 'engineSize']

scaler = StandardScaler()

df_scaled = df.copy()

df_scaled[numeric_features] = scaler.fit_transform(df[numeric_features])

print(df_scaled[numeric_features].head())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

# Load Dataset
df = pd.read_csv("ford_car_dataset.csv")

# Remove Missing Values
df = df.dropna()

# Remove Duplicates
df = df.drop_duplicates()

# Histograms
df[['price','mileage','year','engineSize','mpg']].hist(figsize=(12,8))
plt.tight_layout()
plt.show()

# Count Plots
for col in ['model','fuelType','transmission']:
    plt.figure(figsize=(8,5))
    sns.countplot(x=col, data=df)
    plt.xticks(rotation=45)
    plt.show()

# Heatmap
plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.show()

# Input and Output Features
X = df.drop('price', axis=1)
y = df['price']

# Encoding
X = pd.get_dummies(X, drop_first=True)

# Scaling
scaler = StandardScaler()

numeric_cols = ['year','mileage','tax','mpg','engineSize']
X[numeric_cols] = scaler.fit_transform(X[numeric_cols])

print(X.head())
print(y.head())